name: Bitwise GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: make run_tests

      - name: Generate changelog
        if: github.ref == 'refs/heads/main'
        run: |
          npm install -g standard-version
          standard-version
